baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'zeisch.blog'
theme = 'paper'

[params]
  color = 'wheat'                           # linen, wheat, gray, light

  # header social icons
  twitter = 'MTROVO'
  github = 'mtrovo'                 # github.com/YOUR_GITHUB_ID
  linkedin = 'moisestrovo'             # linkedin.com/in/YOUR_LINKEDIN_ID
  rss = true                                # show rss icon

  name = 'Moises Trovo'
  bio = 'another bunch of atoms floating around a giant fireball'

  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = false              # disable post navigation
  monoDarkIcon = true